[[cells]]
name = "auth"
enable_type_id = false
location = { file = "../../deps/auth" }

[[cells]]
name = "spillman-lock"
enable_type_id = true
location = { file = "../../build/release/spillman-lock" }

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
hash_type = "type"
args = "0xcca9ffc0c5e4d7431efe37432d1562db18670e16"
